baseurl      = "localhost"
title        = "prono.mbre.es"
languageCode = "es-es"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Pronombres para un lenguaje inclusivo"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "prono.mbre.es"
  keywords = "pronombres, lenguaje neutral, lenguaje inclusivo"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "prono.mbre.es"
    subtitle = "Pronombres para un lenguaje inclusivo"
    keywords = "pronombre"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "prono.mbre.es"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "ella"
    name       = "ella"
    url        = "/ella"

  [[menu.main]]
    identifier = "el"
    name       = "él"
    url        = "/el"

  [[menu.main]]
    identifier = "elle"
    name       = "elle"
    url        = "/elle"
